### ISSUE TITLE
Support AT-TLS configuration

### ISSUE THREAD

**Issue by Marty850** [IBM/db2forzosdeveloperextension-about#69]
We use AT-TLS to configure secure https communication for web applications on z/OS. The benefit of using at-tls is that our
security admin can manage all security related configurations of all applications running on z/OS in at-tls. So there is no need to change multiple configuration files of multiple products.

Unfortunately tuningServices doesn't support a at-tls configuration yet. I tried to different ways to configure it:

a) set httpsPort and enable a AT-TLS configuration for this port results in:
Error in VSCode: 

`Socket hung up`

Error in tuningServices:
```
ÝERROR   ¨ CWWKO0801E: Unable to initialize SSLconnection.
Unauthorized access  was denied or security settings have expired.
Exception is javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
 at com.ibm.jsse2.aj.i(aj.java:11)
 at com.ibm.jsse2.aj.a(aj.java:104)
 at com.ibm.jsse2.bg.f(bg.java:134)
 at com.ibm.jsse2.bg.e(bg.java:25)
 at com.ibm.jsse2.bg.unwrap(bg.java:11)
 at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:11)
 at com.ibm.ws.channel.ssl.internal.SSLConnectionLink.readyInbound(SSLConnectionLink.java:560)
 at Ýinternal classes¨
```
I suggest the cause ist that the webserver and AT-TLS services both try to encrypt the communication.

b) deactivate httpsPort and set httpPort to the port that is defined in AT-TLS
AT-TLS does it's job and manages that a secure connection is used. VSCode still connects to tuningServices via https but if you tune a SQL a http-URL is returned as result and that of cause is not possible to reach.

Please support using AT-TLS for the tuningServices.

**Comment by Marty850** [comment]
Hi, could you please give me a short status of that issue?

**Comment by katsoohoo** [comment]
Hi @Marty850,

We are currently working with the SQL Tuning Services team to get this fixed and tested with the extension. We can provide you a more detailed update early next month.

**Comment by katsoohoo** [comment]
Hi @Marty850,

We have published official documentation on how to configure AT-TLS with SQL Tuning Services. Please take a look - https://www.ibm.com/docs/en/db2-for-zos/12?topic=services-configuring-tls
