### ISSUE TITLE
Using different explain tables

### ISSUE THREAD

**Issue by Rune-Christensen** [IBM/db2forzosdeveloperextension-about#80]
In our organization we are using individual explain tables.
This means that when I use the tuning features, I get a privilege issue, because I do not have access to DB2OSC.PLAN_TABLE.
I therefore would like a change that enables me to change DB2OSC to my user credentials, or something else entirely.

This is blocking adoption of the extension at my workplace. 

Thanks
/Rune

**Comment by katsoohoo** [comment]
Hi @Rune-Christensen,

You can specify the explain table schema used when tuning SQLs by right-clicking on a file, clicking **SQL Tuning Options**, and changing the **SQLID** field.

**Comment by Rune-Christensen** [comment]
Hi @katsoohoo 

Thank you for your reply.
The SQLID field changes the id of the user trying to access DB2OSC.PLAN_TABLE.
I need to be able to change DB2OSC.PLAN_TABLE to userID.PLAN_TABLE.

I also tried changing "current maintained table types for optimization" to "user", but still it is DB2OSC.PLAN_TABLE that it tries to access.

Regards
Rune

**Comment by katsoohoo** [comment]
Hi @Rune-Christensen,

I realized the field name "SQLID" may be misleading. This field affects the authorization ID of the process and the explain table schema. Can you give it a try?

I've tried to set SQLID and it seems to be using that as the explain table schema.
![Screen Shot 2022-04-21 at 10 35 50](https://user-images.githubusercontent.com/5027555/164518365-2214462f-f3e9-455a-8f08-20649213c4f5.png)
![Screen Shot 2022-04-21 at 10 36 25](https://user-images.githubusercontent.com/5027555/164518439-5ca32778-c19e-4a7d-bf82-ecb02c4afb9a.png)

**Comment by Rune-Christensen** [comment]
Hi @katsoohoo 
I did try what you suggest, I didn't just read the description. 
No matter what I enter into SQLID, it does not work.
If I remove my user in SQLID, it defaults to accessing with my userid, on DB2OSC.PLAN_TABLE.
If I add my user in SQLID, it still tries to access DB2OSC.PLAN_TABLE.
If I add something else in SQLID, I get an SQLCODE -553, which is fair, since the SQLID does not exist.

My best guess is that DB2OSC.PLAN_TABLE is accessed first, and then it switches to myuser.PLAN_TABLE.

The error I get:
![image](https://user-images.githubusercontent.com/26797797/164686771-5c47335e-665b-4ecf-a824-7ac7bbc01e83.png)
Regards
Rune

**Comment by katsoohoo** [comment]
Hi @Rune-Christensen,

Thank you for clarifying your steps. I would like to get a better understanding of you are trying to do. The [`DB2OSC` schema seems to be associated with packages for tuning query workloads](https://www.ibm.com/docs/en/data-studio/4.1.1?topic=SS62YD_4.1.1/com.ibm.datatools.qrytune.installconfig.doc/topics/packages.html). Are you trying to perform tuning on workloads?

**Comment by katsoohoo** [comment]
@Rune-Christensen Additionally, can you also provide [SQL Tuning Services logs](https://www.ibm.com/docs/en/db2-for-zos/12?topic=services-troubleshooting) to help with debugging the issue?

**Comment by Rune-Christensen** [comment]
Hi @katsoohoo 

I am trying to invoke visual explain.
Select a SQL in a program, right click, and select:
![image](https://user-images.githubusercontent.com/26797797/165515921-36922fba-75e2-4bce-a2ee-37d963d3cb73.png)

Mark of Visual Explain, and hit the tune button:
![image](https://user-images.githubusercontent.com/26797797/165516010-ad90992f-454a-4bf1-8450-9f27d00eaf54.png)

Working on getting the logs.

**Comment by Rune-Christensen** [comment]
Logs:
`  FOR FETCH ONLY, RETURN_VIRTUAL_INDEXES=NO, QUERYNO=111, GET_ARCHIVE=N, QUERY_ID=-1, PROFILE_NAME=SYSV, JOB_NAME=QUERY9891, SQLID=UBIRUC, TUNINGTYPE=SQL_BASED, WTI_JOB_ID=1731335158508818432, QUERY_ACCELERATION=NONE, TUNING_START_TS=2022-04-28 07:11:13.969, RETURN_ALL_COLUMN_STATS=NO, REEXPLAIN=YES, MQT_AGE=0}
[4/28/22 7:11:14:167 GMT] 0000004e SystemOut                                                    O 07:11:14.167 T.S [Default Executor-thread-16] [com.ibm.db2zos.tuningservice.serviceimpl.TransactionManager](closeTransaction:106) INFO  -- TransactionManager closeTransaction metaDBConn -1399582986
[4/28/22 7:11:14:273 GMT] 0000007a SystemOut                                                    O 07:11:14.272 T.S [Thread-30] [com.ibm.aps.tools.dsoe.common.da.DAConst](exceptionTraceOnly:278) ERROR -- 4
[4/28/22 7:11:14:300 GMT] 0000007a SystemOut                                                    O 07:11:14.299 T.S [Thread-30] [com.ibm.aps.tools.dsoe.explain.zos.util.EPLogTracer](exceptionTraceOnly:170) ERROR -- 3
[4/28/22 7:11:14:312 GMT] 0000007a SystemOut                                                    O 07:11:14.311 T.S [Thread-30] [com.ibm.aps.tools.dsoe.common.da.DAConst](exceptionTraceOnly:278) ERROR -- 4
[4/28/22 7:11:14:322 GMT] 0000007a SystemOut                                                    O 07:11:14.322 T.S [Thread-30] [com.ibm.aps.tools.dsoe.common.admin.exception.DBCFGExceptionMapper](mapException:326) INFO  -- 0 com.ibm.aps.tools.dsoe.common.admin.exception.DBCFGExceptionMapper.mapException(OSCSQLException
[4/28/22 7:11:14:327 GMT] 0000007a SystemOut                                                    O 07:11:14.323 T.S [Thread-30] [com.ibm.aps.tools.dsoe.common.admin.exception.DBCFGExceptionMapper](mapException:341) ERROR -- 21 com.ibm.aps.tools.dsoe.common.admin.exception.DBCFGExceptionMapper.mapException(OSCSQLException
com.ibm.db2.jcc.am.SqlSyntaxErrorException: UBIRUC DOES NOT HAVE THE PRIVILEGE TO PERFORM OPERATION INSERT ON OBJECT DB2OSC.PLAN_TABLE. SQLCODE=-551, SQLSTATE=42501, DRIVER=4.26.14
	at com.ibm.db2.jcc.am.b7.a(b7.java:810) ~[db2jcc4-4.26.14.jar:?]
	at com.ibm.db2.jcc.am.b7.a(b7.java:66) ~[db2jcc4-4.26.14.jar:?]
	at com.ibm.db2.jcc.am.b7.a(b7.java:140) ~[db2jcc4-4.26.14.jar:?]
	at com.ibm.db2.jcc.am.k4.c(k4.java:2824) ~[db2jcc4-4.26.14.jar:?]
	at com.ibm.db2.jcc.am.k4.d(k4.java:2808) ~[db2jcc4-4.26.14.jar:?]
	at com.ibm.db2.jcc.am.k4.b(k4.java:2168) ~[db2jcc4-4.26.14.jar:?]
	at com.ibm.db2.jcc.t4.ab.k(ab.java:446) ~[db2jcc4-4.26.14.jar:?]
	at com.ibm.db2.jcc.t4.ab.c(ab.java:104) ~[db2jcc4-4.26.14.jar:?]
	at com.ibm.db2.jcc.t4.p.b(p.java:38) ~[db2jcc4-4.26.14.jar:?]
	at com.ibm.db2.jcc.t4.av.h(av.java:124) ~[db2jcc4-4.26.14.jar:?]
	at com.ibm.db2.jcc.am.k4.ak(k4.java:2163) ~[db2jcc4-4.26.14.jar:?]
	at com.ibm.db2.jcc.am.k4.a(k4.java:3366) ~[db2jcc4-4.26.14.jar:?]
	at com.ibm.db2.jcc.am.k4.c(k4.java:788) ~[db2jcc4-4.26.14.jar:?]
	at com.ibm.db2.jcc.am.k4.executeUpdate(k4.java:767) ~[db2jcc4-4.26.14.jar:?]
	at org.apache.commons.dbcp2.DelegatingStatement.executeUpdate(DelegatingStatement.java:341) ~[commons-dbcp2-2.7.0.jar:2.7.0]
	at com.ibm.aps.tools.connection.util.internal.ConnectionWrapper$StatementWrapper.executeUpdate(ConnectionWrapper.java:631) ~[com.ibm.aps.tools.connection.util-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at com.ibm.aps.tools.dsoe.common.da.DynamicSQLExecutorImpl.executeUpdateBody(DynamicSQLExecutorImpl.java:313) ~[com.ibm.aps.tools.dsoe.common-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at com.ibm.aps.tools.dsoe.common.da.DynamicSQLExecutorImpl.executeUpdate(DynamicSQLExecutorImpl.java:255) ~[com.ibm.aps.tools.dsoe.common-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at com.ibm.aps.tools.dsoe.explain.zos.impl.ExplainThread.executeExplainCommand(ExplainThread.java:1662) [com.ibm.aps.tools.dsoe.explain.zos-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at com.ibm.aps.tools.dsoe.explain.zos.impl.ExplainThread.explain(ExplainThread.java:1574) [com.ibm.aps.tools.dsoe.explain.zos-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at com.ibm.aps.tools.dsoe.explain.zos.impl.ExplainThread.explain(ExplainThread.java:1335) [com.ibm.aps.tools.dsoe.explain.zos-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at com.ibm.aps.tools.dsoe.explain.zos.impl.ExplainThread.commonProcess(ExplainThread.java:414) [com.ibm.aps.tools.dsoe.explain.zos-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at com.ibm.aps.tools.dsoe.explain.zos.impl.ExplainThread.run(ExplainThread.java:7599) [com.ibm.aps.tools.dsoe.explain.zos-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
[4/28/22 7:11:14:328 GMT] 0000007a SystemOut                                                    O 07:11:14.328 T.S [Thread-30] [com.ibm.aps.tools.dsoe.common.admin.exception.DBCFGExceptionMapper](mapException:430) INFO  -- 21 com.ibm.aps.tools.dsoe.common.admin.exception.DBCFGExceptionMapper.mapException(OSCSQLException
[4/28/22 7:11:14:328 GMT] 0000007a SystemOut                                                    O 07:11:14.328 T.S [Thread-30] [com.ibm.aps.tools.dsoe.explain.zos.util.EPLogTracer](exceptionTraceOnly:170) ERROR -- 3
[4/28/22 7:11:14:328 GMT] 0000007a SystemOut                                                    O 07:11:14.328 T.S [Thread-30] [com.ibm.aps.tools.dsoe.explain.zos.util.EPLogTracer](exceptionLogTrace:44) ERROR -- 3
[4/28/22 7:11:14:548 GMT] 00000047 SystemOut                                                    O 07:11:14.548 T.S [Default Executor-thread-15] [com.ibm.db2zos.tuningservice.serviceimpl.TransactionManager](startTransaction:52) INFO  -- TransactionManager startTransaction metaDBConn 1856189003 1
[4/28/22 7:11:14:552 GMT] 00000047 SystemOut                                                    O 07:11:14.552 T.S [Default Executor-thread-15] [com.ibm.db2zos.tuningservice.serviceimpl.TransactionManager](closeTransaction:106) INFO  -- TransactionManager closeTransaction metaDBConn 1856189003
[4/28/22 7:11:14:763 GMT] 00000077 SystemOut                                                    O 07:11:14.763 T.S [apg-service-1] [com.ibm.db2zos.tuningservice.serviceimpl.TransactionManager](closeTransaction:106) INFO  -- TransactionManager closeTransaction metaDBConn 430326980
[4/28/22 7:11:14:766 GMT] 00000077 SystemOut                                                    O 07:11:14.764 T.S [apg-service-1] [com.ibm.db2zos.tuningservice.runner.VERunner](executeAsync:76) ERROR -- tuneSingleQuery ExplainFailException
com.ibm.db2zos.tuningservice.exception.ExplainFailException: The Selected Feature or Features Could Not Run

EXPLAIN information could not be collected for the SQL statement. The selected feature or features depend on EXPLAIN information, and therefore could not run.

Explanation:
Your user ID does not have a required privilege on a database object. Refer to the "Returned message" section below.

User response:
Ask your database administrator to grant the required privilege on the object to your user ID. Then, try again to run the feature or features.

Returned message:
UBIRUC DOES NOT HAVE THE PRIVILEGE TO PERFORM OPERATION INSERT ON OBJECT DB2OSC.PLAN_TABLE. SQLCODE=-551, SQLSTATE=42501, DRIVER=4.26.14

The Db2 information center contains more information about SQL error -551.
	at com.ibm.db2zos.tuningservice.serviceimpl.TuneQueryService.callExplain(TuneQueryService.java:196) ~[TuningService.spring:?]
	at com.ibm.db2zos.tuningservice.serviceimpl.TuneQueryService.tuneSingleQuery(TuneQueryService.java:161) ~[TuningService.spring:?]
	at com.ibm.db2zos.tuningservice.runner.VERunner.executeAsync(VERunner.java:63) [TuningService.spring:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90) ~[?:1.8.0]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55) ~[?:1.8.0]
	at java.lang.reflect.Method.invoke(Method.java:508) ~[?:1.8.0]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) [spring-aop-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) [spring-aop-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) [spring-aop-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$$Lambda$701/0x000000001e3cb000.call(Unknown Source) [spring-aop-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:277) [?:1.8.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160) [?:1.8.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:1.8.0]
	at java.lang.Thread.run(Thread.java:825) [?:2.9 (01-04-2022)]
Caused by: com.ibm.aps.tools.dsoe.explain.zos.exception.ExplainException
	at com.ibm.aps.tools.dsoe.explain.zos.impl.ExplainThread.executeExplainCommand(ExplainThread.java:1705) ~[com.ibm.aps.tools.dsoe.explain.zos-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at com.ibm.aps.tools.dsoe.explain.zos.impl.ExplainThread.explain(ExplainThread.java:1574) ~[com.ibm.aps.tools.dsoe.explain.zos-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at com.ibm.aps.tools.dsoe.explain.zos.impl.ExplainThread.explain(ExplainThread.java:1335) ~[com.ibm.aps.tools.dsoe.explain.zos-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at com.ibm.aps.tools.dsoe.explain.zos.impl.ExplainThread.commonProcess(ExplainThread.java:414) ~[com.ibm.aps.tools.dsoe.explain.zos-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at com.ibm.aps.tools.dsoe.explain.zos.impl.ExplainThread.run(ExplainThread.java:7599) ~[com.ibm.aps.tools.dsoe.explain.zos-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
[4/28/22 7:11:14:768 GMT] 00000077 SystemOut                                                    O 07:11:14.768 T.S [apg-service-1] [com.ibm.db2zos.tuningservice.serviceimpl.TransactionManager](startTransaction:52) INFO  -- TransactionManager startTransaction metaDBConn -1891224579 1
[4/28/22 7:11:14:771 GMT] 00000077 SystemOut                                                    O 07:11:14.771 T.S [apg-service-1] [com.ibm.db2zos.tuningservice.serviceimpl.TransactionManager](closeTransaction:106) INFO  -- TransactionManager closeTransaction metaDBConn -1891224579
[4/28/22 7:11:14:773 GMT] 00000077 SystemOut                                                    O 07:11:14.773 T.S [apg-service-1] [com.ibm.db2zos.tuningservice.serviceimpl.TransactionManager](startTransaction:52) INFO  -- TransactionManager startTransaction metaDBConn -1626827957 1
[4/28/22 7:11:14:792 GMT] 00000077 SystemOut                                                    O 07:11:14.792 T.S [apg-service-1] [com.ibm.db2zos.tuningservice.serviceimpl.TransactionManager](closeTransaction:106) INFO  -- TransactionManager closeTransaction metaDBConn -1626827957
[4/28/22 7:11:14:793 GMT] 00000077 SystemOut                                                    O 07:11:14.793 T.S [apg-service-1] [com.ibm.db2zos.tuningservice.runner.VERunner](executeAsync:107) INFO  -- VERunner done
[4/28/22 7:11:15:143 GMT] 00000044 SystemOut                                                    O 07:11:15.142 T.S [Default Executor-thread-12] [com.ibm.db2zos.tuningservice.serviceimpl.TransactionManager](startTransaction:52) INFO  -- TransactionManager startTransaction metaDBConn -564717902 1
[4/28/22 7:11:15:146 GMT] 00000044 SystemOut                                                    O 07:11:15.146 T.S [Default Executor-thread-12] [com.ibm.db2zos.tuningservice.serviceimpl.TransactionManager](closeTransaction:106) INFO  -- TransactionManager closeTransaction metaDBConn -564717902
[4/28/22 7:11:17:492 GMT] 0000006f SystemOut                                                    O 07:11:17.492 T.S [Default Executor-thread-32] [com.ibm.db2zos.tuningservice.serviceimpl.TransactionManager](startTransaction:52) INFO  -- TransactionManager startTransaction metaDBConn -1166579212 1
[4/28/22 7:11:17:497 GMT] 0000006f SystemOut                                                    O 07:11:17.497 T.S [Default Executor-thread-32] [com.ibm.db2zos.tuningservice.serviceimpl.TransactionManager](closeTransaction:106) INFO  -- TransactionManager closeTransaction metaDBConn -1166579212
`

**Comment by Nina0408** [comment]
hi @katsoohoo , Can you please provide the request body when VSC side calls VE API?

**Comment by Nina0408** [comment]
@Rune-Christensen Could you share me with the SQL text that you tuned which causes this error? 

I can recreate the same error as you got in below scenario:

- The SQL I tuned is : **select * from sysibm.systables**

- and SQLID I set is **TMSDEV**, whose privilege is lower than sysibm needs.

So I will get below error like yours:

`The Selected Feature or Features Could Not Run  EXPLAIN information could not be collected for the SQL statement. The selected feature or features depend on EXPLAIN information, and therefore could not run.  Explanation: Your user ID does not have a required privilege on a database object. Refer to the \"Returned message\" section below.  User response: Ask your database administrator to grant the required privilege on the object to your user ID. Then, try again to run the feature or features.  Returned message: TMSDEV DOES NOT HAVE THE PRIVILEGE TO PERFORM OPERATION SELECT ON OBJECT SYSIBM.SYSTABLES. SQLCODE=-551, SQLSTATE=42501, DRIVER=4.26.14  The Db2 information center contains more information about SQL error -551.`

Which says SQLID ( if no SQLID specified, then connection use id) need to have the priviledge to execute the SQL text tuned.

Thanks!

**Comment by Rune-Christensen** [comment]
@Nina0408 

I would rather not share our SQL in a public domain.
But I can recreate the issue with **select * from sysibm.systables**
This gives the same error as I posted above.
Our users have access to sysibm.* tables, so that is not the issue.

/Rune

**Comment by Rune-Christensen** [comment]
I do not know if this is relevant. But I can force the same error in Data Studio 4.1.4
Doing visual explain on a known package like this:
![image](https://user-images.githubusercontent.com/26797797/165900012-0d40b39c-92ec-4967-a17f-e7a8bb0f9824.png)
Does not give an error.

But requesting a re-explain like this:
![image](https://user-images.githubusercontent.com/26797797/165900094-3868e3af-13b7-4d43-81ef-29ea84c0ecdd.png)
Gives the exact same -551 on db2osc.plan_table.

**Comment by zhaoxq** [comment]
Thanks for quick response @Rune-Christensen .
The question is that does the sql you tuned have reference to DB2OSC.PLAN_TABLE?

**Comment by Rune-Christensen** [comment]
No, it does not, and it should be clear, since I can recreate the issue with **select * from sysibm.systables** :-)

**Comment by zhaoxq** [comment]
@Rune-Christensen  are you ok to have a web meeting with us?

**Comment by Nina0408** [comment]
@Rune-Christensen Hi Rune, You mean you can recreate it by tune **select * from sysibm.systables** with error says : ${ID} DOES NOT HAVE THE PRIVILEGE TO PERFORM OPERATION INSERT ON OBJECT **DB2OSC.PLAN_TABLE**.

**Comment by Rune-Christensen** [comment]
@Nina0408 That is correct.

**Comment by zhaoxq** [comment]
@Rune-Christensen  if you can join webex now, please join with this link https://ibm.webex.com/meet/zhaoxq.  or give us any webex link of yours.

If the time slot does not work for you, please suggest a new timing, thanks.

**Comment by Rune-Christensen** [comment]
Success, thank you for helping us figuring this out.
The issue was that my userId.plan_table was an alias for db2osc.plan_table.
We found several other users with the same issue, these are being fixed :-)
Now we can roll out the extension out to everyone here, thanks again :-)
